package gui;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Edunaldo
 */
public class App extends javax.swing.JFrame {
    
    private Hilo tiempo;
    
    public App() {
        initComponents();
        tiempo = new Hilo();
        tiempo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEquipo1 = new javax.swing.JButton();
        btnEquipo2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPorcentajeEquipo1 = new javax.swing.JLabel();
        lblPorcentajeEquipo2 = new javax.swing.JLabel();
        lblTiempoPartido = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnEquipo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEquipo1.setText("SANTA AMELIA F.C");
        btnEquipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipo1ActionPerformed(evt);
            }
        });

        btnEquipo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEquipo2.setText("REAL MADRID F.C");
        btnEquipo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipo2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("PORCENTAJE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("PORCENTAJE");

        lblPorcentajeEquipo1.setText("PORCEN1");

        lblPorcentajeEquipo2.setText("PORCEN2");

        lblTiempoPartido.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTiempoPartido.setText("TIEMPO PARTIDO");
        lblTiempoPartido.setToolTipText("");
        lblTiempoPartido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("COMENZAR PARTIDO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEquipo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblPorcentajeEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTiempoPartido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPorcentajeEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEquipo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTiempoPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPorcentajeEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPorcentajeEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEquipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipo1ActionPerformed
        tiempo.cambiarEquipo1();
    }//GEN-LAST:event_btnEquipo1ActionPerformed

    private void btnEquipo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipo2ActionPerformed
        tiempo.cambiarEquipo2();
    }//GEN-LAST:event_btnEquipo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEquipo1;
    private javax.swing.JButton btnEquipo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPorcentajeEquipo1;
    private javax.swing.JLabel lblPorcentajeEquipo2;
    private javax.swing.JLabel lblTiempoPartido;
    // End of variables declaration//GEN-END:variables

    private class Hilo extends Thread {

        private int segEquipo1 = 0;
        private int segEquipo2 = 0;
        private boolean equiposeleccionado1;
        private boolean equiposeleccionado2;
        
        public Hilo(){
            equiposeleccionado1 = false;
            equiposeleccionado2 = false;
        }
        
        @Override
        public void run() {
            int seg2 = 0;
            
            for (int min = 0; min <= 90; min++) {
                if (min != 90) {
                    for (int seg = 0; seg < 60; seg++) {
                        seg2++;

                        try {
                            String minuto = (min <= 9 ? "0" + min : Integer.toString(min));
                            String segundos = (seg <= 9 ? "0" + seg : Integer.toString(seg));
                            lblTiempoPartido.setText(minuto + ":" + segundos);
                            if(equiposeleccionado1){
                                aumentarSegEquipo1();
                                int porcentajePosesion = (segEquipo1*100)/seg2;
                                lblPorcentajeEquipo1.setText(Integer.toString(porcentajePosesion));
                            }else if(equiposeleccionado2){
                                aumentarSegEquipo2();
                                int porcentajePosesion = (segEquipo2*100)/seg2;
                                lblPorcentajeEquipo2.setText(Integer.toString(porcentajePosesion));
                            }
                            
                            Thread.sleep(3);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                } else {
                    lblTiempoPartido.setText("90:00");
                }

            }
        }

        public void aumentarSegEquipo1() {
            segEquipo1++;
            System.out.println("equipo 1:"+segEquipo1);
        }
        
        public void aumentarSegEquipo2() {
            segEquipo2++;
            System.out.println("equipo 2:"+segEquipo2);
        }
        
        public void cambiarEquipo1(){
            equiposeleccionado2 = false;
            equiposeleccionado1 = true;
        }
        
        public void cambiarEquipo2(){
            equiposeleccionado1 = false;
            equiposeleccionado2 = true;
            
        }

    }
}
